# Generated by Django 5.1.1 on 2024-11-07 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_discussion", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="student_discussion.chatroom",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
